version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WEBUI_PORT=8080
    volumes:
      - /portainer/Files/AppData/Config/QBitTorrent/config:/config
      - /portainer/Files/AppData/Config/QBitTorrent/downloads:/downloads
    ports:
      - 80809:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
