version: "2.1"
services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /portainer/Files/AppData/Config/Readarr/data:/config
      - /home/pi/Ebooks:/books #optional
      -/home/pi/EbookDownloads:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped
