version: "2.1"
services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - PASSWORD= #optional
      - CLI_ARGS= #optional
    volumes:
      - /portainer/Files/AppData/Config/Calibre/:/config
    ports:
      - 8080:8080
      - 8081:8081
    restart: unless-stopped
