---
# This is an example of how to deploy HomerGX using docker-compose
version: "2"
services:
  homergx:
    image: ghcr.io/georgegedox/homergx:latest
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: homergx
    volumes:
      - /portainer/Files/AppData/Config/HomerGX/assets:/www/assets
    ports:
      - 8090:8080
    #environment:
    #  - UID=1000
    #  - GID=1000
    restart: unless-stopped
